version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
      - DEBUG=True
    volumes:
      - .:/app
    command: python app.py
    restart: unless-stopped
